// This file was generated by ./gamelist.pl (perl 5.030003)

// Declaration of all drivers
#define DRV extern struct BurnDriver
#undef DRV

// Structure containing addresses of all drivers
// Needs to be kept sorted (using the full game name as the key) to prevent problems with the gamelist in Kaillera
static struct BurnDriver* pDriver[] = {
};
